# Generated by Django 5.0.1 on 2024-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='descreption',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=12),
        ),
    ]
