# Generated by Django 5.0.1 on 2024-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(max_length=155),
        ),
    ]
