# Generated by Django 5.0.1 on 2024-01-31 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_trainer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
