# Generated by Django 5.0.1 on 2024-01-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_trainer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='DOB',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
