# Generated by Django 5.0.1 on 2024-02-01 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_enrollment_selectmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectMembership',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan',
            field=models.CharField(max_length=185),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(max_length=55),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainer',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
