# Generated by Django 5.0.1 on 2024-02-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
    ]
